/*
DELETE FROM WF_GenerWorkFlow
DELETE FROM WF_GenerWorkerlist
DELETE FROM  ND501
DELETE FROM  ND502
DELETE FROM  ND599
DELETE FROM  ND5Rpt
*/

SELECT * FROM WF_EmpWorks WHERE WorkID=514

SELECT * FROM WF_GenerWorkFlow
SELECT * FROM WF_GenerWorkerlist
SELECT * FROM WF_EmpWorks 

SELECT * FROM ND501
SELECT * FROM ND502
SELECT * FROM ND599
SELECT * FROM ND5Rpt
